services:
  pg_db:
    image: postgres:latest
    restart: unless-stopped
    container_name: tasket_db
    hostname: ${DB_HOST}
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  api:
    build: .
    container_name: tasket_api
    restart: always
    depends_on:
      - pg_db
    env_file:
      - .env
    environment:
      - DB_HOST=pg_db
    ports:
      - "8000:8000"

volumes:
  postgres_data: